export const UI_TEXT = {
  vi: {
    appName: "DataQuery AI",
    uploadTitle: "Phân tích dữ liệu bằng ngôn ngữ tự nhiên",
    uploadSubtitle: "Tải file lên, hỏi bằng tiếng Việt hoặc tiếng Anh, nhận SQL, bảng kết quả và biểu đồ.",
    dropTitle: "Kéo thả file vào đây",
    dropSubtitle: "hoặc bấm để chọn file từ máy",
    dropActive: "Thả file vào đây",
    uploadLoading: "Đang phân tích file...",
    formats: "Định dạng hỗ trợ",
    schema: "Schema",
    language: "Ngôn ngữ",
    newFile: "Upload file mới",
    suggestions: "Gợi ý",
    suggestionsLoading: "Đang tạo gợi ý từ AI...",
    startTitle: "Bắt đầu phân tích",
    startBody: "Chọn một gợi ý bên trên hoặc nhập câu hỏi về dữ liệu của bạn bên dưới.",
    askPlaceholder: "Hỏi về dữ liệu... ví dụ: Tổng doanh thu theo nhân viên bán hàng",
    composerHint: "Enter để gửi · AI sẽ sinh SQL và biểu đồ tự động",
    chart: "Biểu đồ",
    chartUnavailable: "Biểu đồ",
    table: "Bảng dữ liệu",
    result: "Kết quả",
    sql: "SQL",
    finalSql: "SQL cuối cùng",
    ragPrompt: "Prompt đã ghép RAG",
    noChart: "Không thể vẽ biểu đồ",
    viewTable: "Xem dữ liệu ở tab Bảng dữ liệu",
    noData: "Không có dữ liệu",
    rows: "dòng",
    showingRows: "Hiển thị",
    sqlError: "Lỗi SQL",
    llmError: "Lỗi LLM - đang dùng fallback SQL",
    mockSql: "Mock SQL",
    openSchema: "Mở schema",
    close: "Đóng",
    provider: "Provider",
    rag: "RAG",
    uploadFailed: "Upload thất bại. Kiểm tra backend đã chạy chưa.",
    queryFailed: "Có lỗi xảy ra khi truy vấn.",
    ollamaWarning: "Ollama đang được chọn nhưng chưa chạy. Hãy khởi động Ollama và pull model để dùng AI local.",
    deepseekWarning: "Chưa có DeepSeek API key. SQL sẽ dùng mock mode nếu không có fallback.",
    autoWarning: "Auto mode cần DeepSeek API key hoặc Ollama đang chạy. Mock SQL sẽ được dùng làm fallback.",
  },
  en: {
    appName: "DataQuery AI",
    uploadTitle: "Analyze data with natural language",
    uploadSubtitle: "Upload a file, ask in English or Vietnamese, and get SQL, tables, and charts.",
    dropTitle: "Drag and drop a file here",
    dropSubtitle: "or click to choose a local file",
    dropActive: "Drop the file here",
    uploadLoading: "Analyzing file...",
    formats: "Supported formats",
    schema: "Schema",
    language: "Language",
    newFile: "Upload new file",
    suggestions: "Suggestions",
    suggestionsLoading: "Generating AI suggestions...",
    startTitle: "Start analyzing",
    startBody: "Choose a suggestion above or ask a question about your data below.",
    askPlaceholder: "Ask about your data... e.g. Total revenue by sales representative",
    composerHint: "Press Enter to send · AI will generate SQL and charts automatically",
    chart: "Chart",
    chartUnavailable: "Chart",
    table: "Data table",
    result: "Result",
    sql: "SQL",
    finalSql: "Final SQL",
    ragPrompt: "RAG-composed prompt",
    noChart: "Unable to render chart",
    viewTable: "View the data in the Data table tab",
    noData: "No data",
    rows: "rows",
    showingRows: "Showing",
    sqlError: "SQL error",
    llmError: "LLM error - using fallback SQL",
    mockSql: "Mock SQL",
    openSchema: "Open schema",
    close: "Close",
    provider: "Provider",
    rag: "RAG",
    uploadFailed: "Upload failed. Check that the backend is running.",
    queryFailed: "An error occurred while querying.",
    ollamaWarning: "Ollama is selected but not running. Start Ollama and pull the model to use local AI.",
    deepseekWarning: "DeepSeek API key is missing. SQL will use mock mode if there is no fallback.",
    autoWarning: "Auto mode needs either a DeepSeek API key or a running Ollama model. Mock SQL will be used as fallback.",
  },
};

export const getText = (language = "vi") => UI_TEXT[language] || UI_TEXT.vi;
